notifications:
  slack: brainstorm-etna:hMgNrjhxmXb6CpKKRe5e6oTZ
language: c
sudo: true
before_install:
  - export PATH=~/usr/bin:$PATH
install:
  - sudo apt-get install libsdl2-2.0-0 libsdl2-dev libsdl2-image-2.0-0 libsdl2-image-dev libsdl2-mixer-2.0-0 libsdl2-mixer-dev libsdl2-ttf-2.0-0 libsdl2-ttf-dev
script:
  - make all
group: stable
dist: trusty
os: linux
